Sdk 133 split adapter and demo app
loopme/android-united-sdk pull request #62
Opened 2024-03-06 10:57 UTC by mateusz-polanski

https://loopme.atlassian.net/browse/SDK-133

2024-03-06 11:44 UTC, EpanchinE requested changes

2024-03-06 11:44 UTC, EpanchinE commented on bridges/ironSource/.idea/compiler.xml
Please remove `.idea` folder

2024-03-06 11:44 UTC, EpanchinE commented on bridges/ironSource/adapter/src/androidTest/java/com/loopme/adapter/ExampleInstrumentedTest.java
use same package as for adapter

2024-03-06 11:44 UTC, EpanchinE commented on bridges/ironSource/adapter/src/main/AndroidManifest.xml
Do we need manifest for adapter?

2024-03-06 11:44 UTC, EpanchinE commented on bridges/ironSource/adapter/src/test/java/com/loopme/adapter/ExampleUnitTest.java
> +package com.loopme.adapter;
use same package as for adapter

2024-03-06 11:44 UTC, EpanchinE commented on bridges/ironSource/app/README.md
> +Class Name should be: 'com.loopme.LoopmeCustomAdapter'. <br>
Do not change class name, because it is specified in IronSource documentation

2024-03-06 11:44 UTC, EpanchinE commented on bridges/ironSource/app/build.gradle
> +    implementation project(path: ':loopme-sdk')
L43-44 should be removed, because adapter already has IronSourceSDK and LoopMeUnitedSDK dependency

2024-03-06 11:44 UTC, EpanchinE commented on bridges/ironSource/app/src/androidTest/java/com/loopme/ironsource_75/ExampleInstrumentedTest.java
Seems like folder `ironsource_75` should be removed

2024-03-06 11:44 UTC, EpanchinE commented on bridges/ironSource/app/src/test/java/com/loopme/ironsource_75/ExampleUnitTest.java
Seems like `ironsorce_75` folder should be removed

2024-03-06 13:24 UTC, mateusz-polanski commented on bridges/ironSource/adapter/src/main/AndroidManifest.xml
Nope

2024-03-08 05:46 UTC, EpanchinE approved these changes

2024-03-08 07:16 UTC, merged